### ISSUE TITLE
Dashboard is including results from previously rejected release request

### ISSUE THREAD

**Issue by dzedro** [openSUSE/qem-dashboard#61]
When release request (update) is resubmitted after reject [1], dashboard will still include also old results from previous release request. This is causing trouble because test will not show when you click on the red field [2] -> [3], you have to find them via 'Details for Incident' -> 'Per Incident Results' of the incident [4] -> [5] or if the results are too old and were deleted reviewer will not find them but dashboard will still have record of the failure and block update.
The update would be approved as results at 20220404-1 passed.
[S:M:23085:267929](https://smelt.suse.de/incident/23085/) is one example, but this is happening with all resubmitted updates when there are failures on tests in previous submission.

**[1]**
![Screenshot_2022-04-06_10-42-55](https://user-images.githubusercontent.com/9447312/161936593-0ca8d865-4ad1-4697-aaa4-f457f3358577.png)

**[2]**
![Screenshot_2022-04-06_10-43-24](https://user-images.githubusercontent.com/9447312/161937101-2e0f4a10-a4c6-4ae1-95f5-06dbef226c3b.png)

**[3]**
![Screenshot_2022-04-06_10-43-52](https://user-images.githubusercontent.com/9447312/161937430-0e68bff2-53ec-48b0-9ae0-61a8232c7a5f.png)

**[4]**
![Screenshot_2022-04-06_10-52-42](https://user-images.githubusercontent.com/9447312/161936077-bdce58e9-15ff-4c76-81c0-9312aabc7eac.png)

**[5]**
![Screenshot_2022-04-06_10-46-39](https://user-images.githubusercontent.com/9447312/161937176-34f3bd93-837c-4cc7-8331-119cb02101bd.png)

**Comment by okurz** [comment]
I guess this is the same as https://progress.opensuse.org/issues/109310 , right? As workarounds can we
1. Ask maintenance to create a new, fresh incident, e.g. by a comment in IBS?
1. Manually delete the incident relation key from old openQA test results or just delete the complete openQA jobs or move them to another job group?

**Comment by mimi1vx** [comment]
one of workaround will be deleting old results from dashboard.

**Comment by okurz** [comment]
> one of workaround will be deleting old results from dashboard.

ok, can you provide more specific steps how to do that so that dzedro and others can fix the problem themselves?

**Comment by mimi1vx** [comment]
> ok, can you provide more specific steps how to do that so that dzedro and others can fix the problem themselves?

for now , manually log to database .. select related results and delete them

**Comment by okurz** [comment]
> for now , manually log to database .. select related results and delete them

please be more specific

**Comment by okurz** [comment]
> > for now , manually log to database .. select related results and delete them
> 
> please be more specific

The commands are

```
ssh root@qam2.suse.de
machinectl shell postgresql
sudo -u postgres psql dashboard_db
(wreak havok in here)
```

**Comment by vpelcak** [comment]
Hello people.
I doubt that people would use that workaround. Not everybody has the access to qam2.suse.de and even fewer know what to do to not to cause more harm than help.

Are there any plans to sort this out? It looks rather dangerous.

**Comment by okurz** [comment]
> Hello people. I doubt that people would use that workaround. Not everybody has the access to qam2.suse.de and even fewer know what to do to not to cause more harm than help.

Yes, that is correct. However it is still the best workaround known for the time being.

> Are there any plans to sort this out? It looks rather dangerous.

Yes, this is already currently being worked on: https://progress.opensuse.org/issues/109310
I expect this to be resolved within the next two weeks.

**Comment by kraih** [comment]
Should be resolved by #63.

**Comment by okurz** [comment]
Reopening due to https://github.com/openSUSE/qem-dashboard/pull/63#issuecomment-1108116720
> I guess this is a good thing to have in general, but I don't think it's a general fix for 61. The rerelease can happen the day after

**Comment by coolo** [comment]
For the record: the screenshot Jozef added shows request 266266 of 2022-03-03 and 267929 of 2022-03-21. So I would love to follow the thought process of fixing this issue with a "remove results older than 90 days"

**Comment by kraih** [comment]
I was assured that 90 days was sufficient... but i guess that's not the case after all. So, do we have to watch out for `rr_number` changes of existing incidents, and if it happens clean up all linked aggregate job data?

**Comment by dzedro** [comment]
> I was assured that 90 days was sufficient... but i guess that's not the case after all. So, do we have to watch out for `rr_number` changes of existing incidents, and if it happens clean up all linked aggregate job data right away?

I think that's the way, tests from previous request are outdated, aggregate and single jobs.

**Comment by kraih** [comment]
Opened another progress ticket to track this: https://progress.opensuse.org/issues/110409. Think i already know how to implement it right.

**Comment by kraih** [comment]
Possible solution: https://github.com/openSUSE/qem-dashboard/pull/78

**Comment by kraih** [comment]
The feature has been deployed to production.
